apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: production
  labels:
    app: billing-service
    service: billing
spec:
  type: ClusterIP
  selector:
    app: billing-service
  ports:
  - port: 80
    targetPort: 3003
    protocol: TCP
    name: http
  sessionAffinity: None
