apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: my-saas-chat
  labels:
    app: chat-service
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
  selector:
    app: chat-service
