codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 70%
        threshold: 5%
        base: auto
        if_ci_failed: error

    patch:
      default:
        target: 70%
        threshold: 5%
        base: auto

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/*.test.tsx"
  - "**/*.spec.tsx"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/__tests__/**"
  - "**/tests/**"
  - "**/*.config.ts"
  - "**/*.config.js"
  - "**/coverage/**"

flags:
  unittests:
    paths:
      - backend/services/
      - frontend/src/
    carryforward: true

  auth-service:
    paths:
      - backend/services/auth-service/src/
    carryforward: true

  chat-service:
    paths:
      - backend/services/chat-service/src/
    carryforward: true

  frontend:
    paths:
      - frontend/src/
    carryforward: true
