apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: production
  labels:
    app: chat-service
    service: chat
    version: v1.0
spec:
  replicas: 5
  selector:
    matchLabels:
      app: chat-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: chat-service
        service: chat
        version: v1.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3002"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: chat-service
        image: chat-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3002
          name: http
          protocol: TCP
        env:
        - name: PORT
          value: "3002"
        - name: SERVICE_NAME
          value: "chat-service"
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "384Mi"
            cpu: "300m"
          limits:
            memory: "768Mi"
            cpu: "750m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
