apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: production
  labels:
    app: chat-service
    service: chat
spec:
  type: ClusterIP
  selector:
    app: chat-service
  ports:
  - port: 80
    targetPort: 3002
    protocol: TCP
    name: http
  sessionAffinity: None
