apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
  namespace: production
  labels:
    app: jaeger
spec:
  type: ClusterIP
  selector:
    app: jaeger
  ports:
  - port: 5775
    protocol: UDP
    targetPort: 5775
    name: zipkin-compact
  - port: 6831
    protocol: UDP
    targetPort: 6831
    name: jaeger-compact
  - port: 6832
    protocol: UDP
    targetPort: 6832
    name: jaeger-binary
  - port: 5778
    protocol: TCP
    targetPort: 5778
    name: config-rest
  - port: 16686
    protocol: TCP
    targetPort: 16686
    name: query-http
  - port: 14250
    protocol: TCP
    targetPort: 14250
    name: grpc
  - port: 14268
    protocol: TCP
    targetPort: 14268
    name: http
  - port: 14269
    protocol: TCP
    targetPort: 14269
    name: admin-http
  - port: 9411
    protocol: TCP
    targetPort: 9411
    name: zipkin
