/**
 * MSW Chat Handlers
 * Mocks chat and conversation endpoints
 */

import { http, HttpResponse, delay } from 'msw';
import {
  mockConversations,
  mockUsageStats,
  getConversationsByUserId,
  getConversationById,
  createNewConversation,
  addMessageToConversation,
  type MockConversation,
} from '../fixtures/conversations';
import { getUserByToken } from '../fixtures/user';

const BASE_URL = '/api';

// Helper to extract user from auth header
const getUserFromRequest = (request: Request) => {
  const authHeader = request.headers.get('Authorization');
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return null;
  }
  const token = authHeader.replace('Bearer ', '');
  return getUserByToken(token);
};

// In-memory storage for testing (resets on test restart)
let conversations = [...mockConversations];

export const chatHandlers = [
  // POST /api/chat - Send a chat message and get AI response
  http.post(`${BASE_URL}/chat`, async ({ request }) => {
    await delay(150); // Simulate AI processing time

    const user = getUserFromRequest(request);
    if (!user) {
      return HttpResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const body = await request.json() as {
      conversationId?: string;
      message: string;
      model?: string;
    };
    const { conversationId, message, model = 'gpt-4' } = body;

    if (!message || message.trim().length === 0) {
      return HttpResponse.json(
        { error: 'Message is required' },
        { status: 400 }
      );
    }

    // Find or create conversation
    let conversation: MockConversation;
    if (conversationId) {
      const found = getConversationById(conversationId);
      if (!found || found.userId !== user.id) {
        return HttpResponse.json(
          { error: 'Conversation not found' },
          { status: 404 }
        );
      }
      conversation = found;
    } else {
      // Create new conversation
      conversation = createNewConversation(
        user.id,
        message.slice(0, 50), // Use first 50 chars as title
        model
      );
      conversations.push(conversation);
    }

    // Add user message
    const userMessage = addMessageToConversation(
      conversation.id,
      'user',
      message,
      Math.ceil(message.split(' ').length * 1.3) // Rough token estimate
    );
    conversation.messages.push(userMessage);

    // Generate mock AI response
    const aiResponse = `This is a mock AI response to: "${message}". In a real application, this would be generated by GPT-4.`;
    const aiMessage = addMessageToConversation(
      conversation.id,
      'assistant',
      aiResponse,
      Math.ceil(aiResponse.split(' ').length * 1.3)
    );
    conversation.messages.push(aiMessage);

    conversation.updatedAt = new Date().toISOString();

    return HttpResponse.json({
      conversation: {
        id: conversation.id,
        title: conversation.title,
        model: conversation.model,
      },
      userMessage,
      aiMessage,
      tokensUsed: (userMessage.tokens || 0) + (aiMessage.tokens || 0),
    });
  }),

  // GET /api/conversations - Get all conversations for user
  http.get(`${BASE_URL}/conversations`, async ({ request }) => {
    await delay(100);

    const user = getUserFromRequest(request);
    if (!user) {
      return HttpResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const userConversations = getConversationsByUserId(user.id);

    return HttpResponse.json({
      conversations: userConversations.map(conv => ({
        id: conv.id,
        title: conv.title,
        model: conv.model,
        messageCount: conv.messages.length,
        lastMessage: conv.messages[conv.messages.length - 1]?.content || null,
        createdAt: conv.createdAt,
        updatedAt: conv.updatedAt,
      })),
      total: userConversations.length,
    });
  }),

  // GET /api/conversations/:id - Get single conversation with messages
  http.get(`${BASE_URL}/conversations/:id`, async ({ request, params }) => {
    await delay(100);

    const user = getUserFromRequest(request);
    if (!user) {
      return HttpResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const { id } = params;
    const conversation = getConversationById(id as string);

    if (!conversation || conversation.userId !== user.id) {
      return HttpResponse.json(
        { error: 'Conversation not found' },
        { status: 404 }
      );
    }

    return HttpResponse.json({
      conversation: {
        id: conversation.id,
        title: conversation.title,
        model: conversation.model,
        messages: conversation.messages,
        createdAt: conversation.createdAt,
        updatedAt: conversation.updatedAt,
      },
    });
  }),

  // PATCH /api/conversations/:id - Update conversation (e.g., title)
  http.patch(`${BASE_URL}/conversations/:id`, async ({ request, params }) => {
    await delay(50);

    const user = getUserFromRequest(request);
    if (!user) {
      return HttpResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const { id } = params;
    const conversation = conversations.find(c => c.id === id && c.userId === user.id);

    if (!conversation) {
      return HttpResponse.json(
        { error: 'Conversation not found' },
        { status: 404 }
      );
    }

    const body = await request.json() as { title?: string };
    const { title } = body;

    if (title) {
      conversation.title = title;
      conversation.updatedAt = new Date().toISOString();
    }

    return HttpResponse.json({
      conversation: {
        id: conversation.id,
        title: conversation.title,
        model: conversation.model,
        updatedAt: conversation.updatedAt,
      },
    });
  }),

  // DELETE /api/conversations/:id - Delete conversation (soft delete)
  http.delete(`${BASE_URL}/conversations/:id`, async ({ request, params }) => {
    await delay(50);

    const user = getUserFromRequest(request);
    if (!user) {
      return HttpResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const { id } = params;
    const conversation = conversations.find(c => c.id === id && c.userId === user.id);

    if (!conversation) {
      return HttpResponse.json(
        { error: 'Conversation not found' },
        { status: 404 }
      );
    }

    // Soft delete
    conversation.deletedAt = new Date().toISOString();

    return HttpResponse.json({
      message: 'Conversation deleted successfully',
      deletedAt: conversation.deletedAt,
    });
  }),

  // GET /api/usage - Get user's usage statistics
  http.get(`${BASE_URL}/usage`, async ({ request }) => {
    await delay(50);

    const user = getUserFromRequest(request);
    if (!user) {
      return HttpResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const usage = mockUsageStats[user.id as keyof typeof mockUsageStats] || {
      totalTokens: 0,
      totalMessages: 0,
      totalConversations: 0,
      currentMonth: {
        tokens: 0,
        messages: 0,
        conversations: 0,
      },
    };

    return HttpResponse.json({
      usage,
    });
  }),

  // Error scenarios
  // POST /api/chat with server error
  http.post(`${BASE_URL}/chat/error`, async () => {
    await delay(100);
    return HttpResponse.json(
      { error: 'AI service unavailable' },
      { status: 503 }
    );
  }),

  // GET /api/conversations/:id with not found
  http.get(`${BASE_URL}/conversations/nonexistent`, async ({ request }) => {
    await delay(50);

    const user = getUserFromRequest(request);
    if (!user) {
      return HttpResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    return HttpResponse.json(
      { error: 'Conversation not found' },
      { status: 404 }
    );
  }),
];
