apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: my-saas-chat
  labels:
    app: billing-service
    component: backend
    tier: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
        component: backend
        tier: application
    spec:
      containers:
      - name: billing
        image: my-saas-chat/billing-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3003
          name: http
          protocol: TCP

        env:
        # Application config
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ENV
        - name: PORT
          value: "3003"
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOG_LEVEL

        # Database URLs
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_URL

        # Stripe API Keys
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys-secret
              key: STRIPE_SECRET_KEY
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: api-keys-secret
              key: STRIPE_WEBHOOK_SECRET
              optional: true

        # Auth service URL
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:3001"

        # Frontend URL (for redirects)
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FRONTEND_URL

        # Jaeger tracing
        - name: JAEGER_AGENT_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: JAEGER_AGENT_HOST
        - name: JAEGER_AGENT_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: JAEGER_AGENT_PORT
        - name: JAEGER_SERVICE_NAME
          value: "billing-service"

        # Optional: Sentry
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: api-keys-secret
              key: SENTRY_DSN
              optional: true

        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3

      # Init container to wait for PostgreSQL
      initContainers:
      - name: wait-for-postgres
        image: postgres:16-alpine
        command:
        - sh
        - -c
        - |
          until pg_isready -h postgres-service -p 5432 -U postgres; do
            echo "Waiting for postgres..."
            sleep 2
          done
