apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: my-saas-chat
  labels:
    app: billing-service
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
    name: http
  selector:
    app: billing-service
